<?php

########################################################################
# Extension Manager/Repository config file for ext: "yag_theme_simpleviewer"
#
# Auto generated by Extbase Kickstarter 2011-01-06
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'YAG Theme Simpleviewer',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Lienert',
	'author_email' => 'daniel@lienert.cc',
	'author_company' => '',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,yag',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>